---
title: "Covid-19 SG"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.width = 10,
                      warning = FALSE,
                      message = FALSE)

library(tidyverse)
library(lubridate)
library(gganimate)

old <- theme_set(theme_bw())
theme_set(theme_bw())
colour1 <- "#F8766D"
colour2 <- "#00BFC4"

theme_set(theme_bw())
themeDate <- theme(axis.text.x = element_text(angle = 90, hjust = 1))

```


### COVID-19 SINGAPORE

```{r}
# import data
df <- readRDS("./data/pt_final.rds")

# today's date
date_today <- ymd(20200421)

```

# Data as at `r as.character(date_today)`

Overview
```{r}
df %>% 
  count(patient_status_update)
```


### Number of cases based on dates confirmed
```{r}
df %>% 
  ggplot(aes(x = date_confirm, fill = exposure)) +
  geom_bar() + 
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day") +
  scale_y_continuous(breaks = scales::pretty_breaks()) +
  themeDate +
  labs(x = "date",
       y = "") +
  theme(legend.direction = "horizontal",
        legend.position= c(0.1, 0.95))
```


### Number of cases by type of exposure

```{r}
df %>% 
  count(date_confirm, exposure) %>% 
  ggplot(aes(x = date_confirm, y = n, fill = exposure)) +
  geom_col() + 
  facet_grid(exposure~., scales = "free_y") +
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day") +
  themeDate + 
  theme(legend.position= c(0.2, 0.9),
        legend.direction = "horizontal") +
  # labs(fill = "exposure") + 
  xlab("date confirmed") + ylab("")

```


### Number of cases by passport type
```{r}
df %>% 
  count(date_confirm, pass_type) %>% 
  ggplot(aes(x = date_confirm, y = n)) +
  geom_col(fill = colour2) + 
  facet_grid(pass_type~., scales = "free_y") +
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day") +
  themeDate + 
  xlab("date confirmed") + ylab("")

```

```{r}
glimpse(mtcars)
```



